title: r1ghrfhd's blog
author: r1ghrfhd blog
tagline: 个人学习记录博客.
email: 3516653160@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  r1ghrfhd | Blog.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://r1ghrfhd.github.io" # the base hostname & protocol for your site, e.g. http://example.com
default: 
  scope:
    path: "public/images"
  values:
    image: true
github_username: r1ghrfhd
highlighter: rouge
svg:
  optimize: true
# Build settings
# theme: minima
date_format: "%Y-%M-%D"
plugins:
  # - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
category_dir: category/
tag_dir: tag/
google_analytics: UA-155788752-1
theme: jekyll-theme-merlot
